name: zebrafish
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - ipython
  - jupyterlab
  - ipywidgets
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - matplotlib
  - ipython
  - ipykernel
  - pandas
  - numpy
  - numba
  - bokeh
  - scikit-image
  - scikit-learn
  - timm
  - hydra-core
  - albumentations
  - kornia
  - datasets>=2.15

