name: zebrafish
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python>=3.10
  - ipython
  - jupyterlab
  - ipywidgets
  - pytorch::pytorch==2
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.8
  - matplotlib
  - ipykernel
  - pandas
  - numpy
  - pyarrow
  - numba
  - bokeh
  - scikit-image
  - scikit-learn
  - timm
  - hydra-core
  - albumentations
  - datasets>=2.15
  - toolz
  - mlflow>=2

  


